
const Q=window.QUESTION_BANK||[];
const app=document.querySelector('#app'),tabs=document.querySelector('#tabs');
const state=JSON.parse(localStorage.getItem('q5007')||'{"done":{},"wrong":{},"exams":[]}');
let session=null,timer=null;
const save=()=>localStorage.setItem('q5007',JSON.stringify(state));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const esc=s=>(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function shell(html,showTabs=true){app.innerHTML=html;tabs.classList.toggle('hidden',!showTabs);window.scrollTo(0,0)}
function home(){let done=Object.keys(state.done).length,wrong=Object.keys(state.wrong).length; shell(`<section class="hero"><div class="eyebrow">5007 QUESTION BANK</div><h1>今天也要稳稳进步</h1><p>已完成 ${done} / ${Q.length} 题 · ${wrong} 道错题待巩固</p></section><div class="section-title"><h2>开始学习</h2><span>离线也能刷</span></div><div class="grid"><button class="action" onclick="startPractice()"><span class="icon">✓</span><b>顺序刷题</b><small>逐题练习，即时解析</small></button><button class="action" onclick="startRandom()"><span class="icon orange">⌁</span><b>随机练习</b><small>打乱题序，强化记忆</small></button><button class="action" onclick="startExam()"><span class="icon red">◷</span><b>模拟考试</b><small>40题 · 45分钟</small></button><button class="action" onclick="wrongPage()"><span class="icon">↻</span><b>错题重练</b><small>${wrong} 道错题</small></button></div><div class="section-title"><h2>章节练习</h2><span>4 个章节</span></div>${chapters().map((c,i)=>`<button class="chapter" onclick="startChapter('${encodeURIComponent(c)}')"><span class="num">${i+1}</span><span><b>${esc(c)}</b><small>${Q.filter(q=>q.chapter===c).length} 道题</small></span></button>`).join('')}<p class="note">“产前发育与致畸因素”章节在原始旧版 Word 中仅提取到两个选项，已按二选一保留。</p>`)}
const chapters=()=>[...new Set(Q.map(q=>q.chapter))];
function makeSession(items,mode){session={items,index:0,mode,answers:{},started:Date.now(),left:45*60};renderQuestion();if(mode==='exam')runTimer()}
function startPractice(){makeSession(Q,'practice')} function startRandom(){makeSession(shuffle(Q),'practice')}
function startChapter(c){makeSession(Q.filter(q=>q.chapter===decodeURIComponent(c)),'practice')}
function startWrong(){let ids=Object.keys(state.wrong);if(!ids.length)return wrongPage();makeSession(Q.filter(q=>ids.includes(q.id)),'practice')}
function startExam(){makeSession(shuffle(Q).slice(0,Math.min(40,Q.length)),'exam')}
function runTimer(){clearInterval(timer);timer=setInterval(()=>{if(!session)return;session.left--;let el=document.querySelector('.timer');if(el)el.textContent=`剩余 ${Math.floor(session.left/60)}:${String(session.left%60).padStart(2,'0')}`;if(session.left<=0)finishExam()},1000)}
function renderQuestion(){let q=session.items[session.index],picked=session.answers[q.id],answered=picked!==undefined,exam=session.mode==='exam';shell(`<div class="topbar"><button class="back" onclick="leaveSession()">‹</button><h2>${exam?'模拟考试':esc(q.chapter)}</h2>${exam?`<span class="timer">剩余 ${Math.floor(session.left/60)}:${String(session.left%60).padStart(2,'0')}</span>`:''}</div><div class="progress"><i style="width:${(session.index+1)/session.items.length*100}%"></i></div><div class="qmeta"><span>第 ${session.index+1} / ${session.items.length} 题</span><span>${q.options.length===2?'二选一':'单选题'}</span></div><div class="question">${esc(q.question)}</div>${q.options.map((o,i)=>`<button class="option ${picked===i?'selected':''} ${!exam&&answered?(i===q.answer?'correct':picked===i?'wrong':''):''}" onclick="choose(${i})"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span></button>`).join('')}${!exam&&answered?`<div class="explain"><b>${picked===q.answer?'回答正确':'回答错误'}</b>\n${esc(q.explanation)}</div>`:''}<button class="primary" onclick="nextQuestion()" ${picked===undefined?'disabled style="opacity:.45"':''}>${session.index===session.items.length-1?(exam?'交卷':'完成练习'):'下一题'}</button>${exam?'<button class="secondary" onclick="nextQuestion(true)">暂不作答</button>':''}`,false)}
function choose(i){let q=session.items[session.index];if(session.mode!=='exam'&&session.answers[q.id]!==undefined)return;session.answers[q.id]=i;if(session.mode!=='exam'){state.done[q.id]=i===q.answer;if(i===q.answer)delete state.wrong[q.id];else state.wrong[q.id]=true;save()}renderQuestion()}
function nextQuestion(skip=false){let q=session.items[session.index];if(!skip&&session.answers[q.id]===undefined)return;if(session.index<session.items.length-1){session.index++;renderQuestion()}else session.mode==='exam'?finishExam():finishPractice()}
function leaveSession(){clearInterval(timer);session=null;home()}
function finishPractice(){let total=session.items.length,correct=session.items.filter(q=>session.answers[q.id]===q.answer).length;session=null;shell(`<div class="card score"><h2>练习完成</h2><div class="ring" style="--score:${correct/total*100}%"><strong>${correct}/${total}</strong></div><p>正确率 ${Math.round(correct/total*100)}%</p><button class="primary" onclick="home()">返回首页</button></div>`,false)}
function finishExam(){if(!session)return;clearInterval(timer);let total=session.items.length,correct=session.items.filter(q=>session.answers[q.id]===q.answer).length;session.items.forEach(q=>{let a=session.answers[q.id];if(a!==undefined){state.done[q.id]=a===q.answer;if(a===q.answer)delete state.wrong[q.id];else state.wrong[q.id]=true}});state.exams.unshift({date:new Date().toLocaleString(),correct,total});state.exams=state.exams.slice(0,20);save();session=null;shell(`<div class="card score"><h2>考试完成</h2><div class="ring" style="--score:${correct/total*100}%"><strong>${Math.round(correct/total*100)}</strong></div><p>${correct} 题正确 · ${total-correct} 题错误</p><button class="primary" onclick="home()">返回首页</button></div>`,false)}
function wrongPage(){let ids=Object.keys(state.wrong);shell(`<div class="topbar"><h2>错题本</h2></div>${ids.length?`<div class="card"><b>共有 ${ids.length} 道错题</b><p class="note">答对后会自动移出错题本。</p><button class="primary" onclick="startWrong()">开始重练</button></div>${Q.filter(q=>ids.includes(q.id)).map(q=>`<div class="card"><small>${esc(q.chapter)} · 第${q.number}题</small><p>${esc(q.question)}</p></div>`).join('')}`:'<div class="empty">暂无错题，继续保持！</div>'}`)}
function stats(){let done=Object.keys(state.done).length,correct=Object.values(state.done).filter(Boolean).length;shell(`<div class="topbar"><h2>学习统计</h2></div><div class="card"><div class="statrow"><span>已练习</span><b>${done} / ${Q.length}</b></div><div class="statrow"><span>当前掌握</span><b>${done?Math.round(correct/done*100):0}%</b></div><div class="statrow"><span>错题数量</span><b>${Object.keys(state.wrong).length}</b></div></div><div class="section-title"><h2>考试记录</h2></div>${state.exams.length?state.exams.map(x=>`<div class="card statrow"><span>${x.date}</span><b>${x.correct}/${x.total}</b></div>`).join(''):'<div class="empty">还没有模拟考试记录</div>'}`)}
tabs.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;({home,practice:startPractice,wrong:wrongPage,stats})[b.dataset.tab]()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});home();
